### ISSUE TITLE
Wrong calculation of value when N >= 11 && fruit < 5

### ISSUE THREAD

**Issue by pesc** [aquilax/nutriscore#1]
Hi

https://github.com/aquilax/nutriscore/blob/14c09a49f2083d268a43d235b07aafe56a897bdb/nutriscore.go#L160

It shouldn't be `negative - fibrePoints - fruitPoints` -> `negative - (fibrePoints + fruitPoints)`

See page 29 of your referenced document

**Comment by aquilax** [comment]
Hi @pesc I think unless I'm missing someting obvious, `negative - fibrePoints - fruitPoints` and `negative - (fibrePoints + fruitPoints)` should be equivalent.

Do you mind providing sample values for which the calculation and expected result?

**Comment by pesc** [comment]
haha, sorry you're totally right!

I guess I was just too tired... 🤦
